kernel: direct
kernel_size: 64
intensity: 0.5

conditioning:
  method: emdps
  params:
    scale: 0.0
    iterations:
      img: 1
      kernel: 5

data:
  name: ffhq
  root: ./data/bottle/test/broken_small/

measurement:
  operator:
    name: inpainting

  noise: 
    name: gaussian
    sigma: 0.02
