# data:
#   name: leather
#   root: ./data/leather/train/good/

data:
  name: capsule
  train_root: ./data/capsule/train/
  test_root: ./data/capsule/test/
  image_path: None

  
# data:
#   name: toothbrush
#   root: ./data/toothbrush/train/good/
# data:
#   name: BraTS
#   root: ./data/BraTS/content/data/
