# data:
#   name: leather
#   root: ./data/leather/train/good/
data:
  name: leather
  train_root: ./data/leather/train/
  test_root: ./data/leather/test/
  image_path: None
  
# data:
#   name: toothbrush
#   root: ./data/toothbrush/train/good/
# data:
#   name: BraTS
#   root: ./data/BraTS/content/data/
