# data:
#   name: leather
#   root: ./data/leather/train/good/
data:
  name: screw
  train_root: ./data/screw/train/
  test_root: ./data/screw/test/
  image_path: None

  
# data:
#   name: toothbrush
#   root: ./data/toothbrush/train/good/
# data:
#   name: BraTS
#   root: ./data/BraTS/content/data/
