# data:
#   name: leather
#   root: ./data/leather/train/good/
# data:
#   name: bottle
#   root: ./data/bottle/train/good/

  
# data:
#   name: toothbrush
#   root: ./data/toothbrush/train/good/
data:
  name: BraTS
  root: ./data/BraTS/content/data/
