# Defaults for image training.

image_size: 128
num_channels: 32
num_res_blocks: 1
channel_mult: ""
learn_sigma: False  
class_cond: False
use_checkpoint: False
attention_resolutions: 16
num_heads: 2
num_head_channels: 32
num_heads_upsample: -1
use_scale_shift_norm: True
dropout: 0.0
resblock_updown: True
use_fp16: False
use_new_attention_order: False
model_path: models/leather_10m.pt
